### ISSUE TITLE
Anyrun cliphist

### ISSUE THREAD

**Issue by ArtemChandragupta** [Cryolitia/nixos-config#1]
Hi! I also want to set up cliphist with anyrun. I already have one with wofi and then I start it with a bind it shows me all my recent clipboard. But if I launch anyrun's stdin mode configured like your, I firstly shows just an input field and I need to print and erase something to actually get a history. So, how you deal with this?

**Comment by Cryolitia** [comment]
Sorry, I haven't use it for a long time, please consider asking upstream.
